### ISSUE TITLE
Arquivo reset.css para o jogo da velha

### ISSUE THREAD

**Issue by ErickFSilvaProg** [ErickFSilvaProg/jogo-da-velha#1]
# Reset CSS
### Esse arquivo auxiliará na estrutura do jogo da velha.

![velha](https://github.com/user-attachments/assets/53affdfa-4a88-401a-bf56-7c12b3964e20)

**Comment by ErickFSilva** [comment]
Sugiro também o uso de bootstrap no layout da página.
