### ISSUE TITLE
Arquivo reset.css

### ISSUE THREAD

**Issue by ErickFSilva** [ErickFSilvaProg/jogo-da-velha#2]
Crie um arquivo .css que reset as pré-configurações dos navegadores.
Esse arquivo auxiliará na estrutura do jogo da velha.

![velha](https://github.com/user-attachments/assets/669458d3-0e75-4df4-981c-ed5aec99c5b4)
https://github.com/ErickFSilvaProg/jogo-da-velha

**Comment by ErickFSilvaProg** [comment]
Obrigado pela dica!
Logo que possível irei proceder com a criação do arquivo.

**Comment by ErickFSilvaProg** [comment]
Procedimento realizado como sugerido.
